### PR TITLE
added azure cloud pricing notebook

### PR DESCRIPTION
**Pull request by sumepati**
## Related Issues and Dependencies
#28
…

## This introduces a breaking change
No
- [ ] Yes
- [ ] No

## This Pull Request implements
1. Added notebook (cloud_price_analysis_azure) for data analysis of Azure cloud pricing
2. The data analysis done for only Azure service 'Virtual Machines'

## Description
This is basic data analysis to get initial feedback on the notebook and also to do hands on the git commit process. 
Azure provides APIs to fetch pricing details. This notebook accesses APIs and downloads JSON file. Basic data analysis is done on JSON file followed by creating dataframe showing region wise max/min prices for Azure service 'Virtual Machines'.

Kindly share feedback on code and also share if any other data analysis can be included in next iterations.

### CODE REVIEW

**Comment by aakankshaduggal** [comment]
@sumepati - Overall the notebook looks great. Added a minor comment. Could you also maybe remove the commented code, that is not being used significantly. Besides that please add a conclusion to this notebook and some future ideas that we might want to start working on.

**Comment by sumepati** [comment]
@aakankshaduggal - Thanks for the review comments, will do pre-commit checks locally and will also incorporate other review comments.

**Comment by sumepati** [comment]
@aakankshaduggal - I have made the changes and also executed pre-commit locally. I did get error for "black-nb" but I unstage and restage the notebook and was able to commit without error and push. I tried creating new pull request but it is taking me to same PR. Kindly let me know. Thanks!

**Comment by aakankshaduggal** [comment]
@sumepati - Thank you for adding new commits, however, I still see that this PR is not able to pass the pre-commit check. I suggest looking at the errors that are being generated when you run the pre-commit locally. They would point you exactly to the filename and the line number where you need to fix the errors.

**Comment by codificat** [comment]
The current pre-commit check failure (copied below) is a recent bug in `black`.

Updating pre-commit configuration to the latest version should avoid that.

You can update the pre-commit configuration locally with `pre-commit autoupdate` (and then add an commit the changes to pre-commit configuration).

An example of such an update: https://github.com/AICoE/summit-2022-octo-keynote/pull/83/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9R46

<details>

<summary>failure details:</summary>

```
 black....................................................................Failed
- hook id: black
- exit code: 1
Traceback (most recent call last):
  File "/opt/app-root/src/.cache/pre-commit/repo362ye6r9/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/opt/app-root/src/.cache/pre-commit/repo362ye6r9/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 1423, in patched_main
    patch_click()
  File "/opt/app-root/src/.cache/pre-commit/repo362ye6r9/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 1409, in patch_click
    from click import _unicodefun
ImportError: cannot import name '_unicodefun' from 'click' (/opt/app-root/src/.cache/pre-commit/repo362ye6r9/py_env-python3/lib/python3.8/site-packages/click/__init__.py) 
```
</details>

**Comment by aakankshaduggal** [comment]
@sumepati - Looks like we have some minor issues that are stopping pre-commit to pass. Could you run `pre-commit` locally and then add the changes made by pre-commit. That should resolve this issue.

**Comment by sumepati** [comment]
@aakankshaduggal 
followed as per your note,
precommit is success when executed locally, Kindly find below snapshot, 
image
Please let me know. Thanks!

**Comment by aakankshaduggal** [comment]
Thanks @sumepati for your PR :smile: 
All looks good to me, let's also add issues to this repository for future work :rocket:

**Comment by sumepati** [comment]
Thanks @aakankshaduggal and team for your support.

**Pull request merged**
