### PR TITLE
Update get-started.md

### PR DESCRIPTION
**Pull request by aakankshaduggal**
## Related Issues and Dependencies

Fixing the JH broken links 

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

… Explain your changes.

### CODE REVIEW

**Review by oindrillac — APPROVED** [review]
/lgtm

**Comment by MichaelClifford** [comment]
LGTM once pre-commit is fixed :)

**Review by pacospace — APPROVED** [review]
lgtm! 💯

**Comment by harshad16** [comment]
Rebase and push for pre-commit issue to get fixed.
@aakankshaduggal

**Pull request merged**
