### PR TITLE
Merge CCO and Cloud-price-analysis

### PR DESCRIPTION
**Pull request by AdiY10**
## Related Issues and Dependencies

…

## This introduces a breaking change

- [ ] Yes
- [ ] No

## This Pull Request implements

… Explain your changes.

### CODE REVIEW

**Comment by aakankshaduggal** [comment]
@AdiY10 - Thank you for adding the commits with new changes, could you please confirm if the pre-commit passes locally?

**Comment by AdiY10** [comment]
the pre-commit passes localy, @aakankshaduggal 

image

**Comment by aakankshaduggal** [comment]
@AdiY10 could you please rebase once, and the pre-commit error should be resolved after that :+1:

**Comment by MichaelClifford** [comment]
Thanks @AdiY10 can you please squash these into 1 commit, then we can merge it! :rocket:

**Comment by AdiY10** [comment]
@MichaelClifford  Done :)

**Review by aakankshaduggal — COMMENTED** [review]
Thanks @AdiY10 :smile: 
/lgtm
/approve

**Pull request merged**
